<?php

/**
 * @file
 * Weixin actions for my blog
 */

/**
 * Implements hook_weixin_router_actions
 */
function weixin_wangxb_weixin_router_actions() {
  $actions = array();
  $actions['subscribe'] = array(
    'title' => 'Subscribe',
    'class' => 'WangxbSubscribeAction',
    'description' => 'The event fire when user subscribe my weixin.',
    'type' => WEIXIN_ROUTER_TYPE_EVENT,
  );
  $actions['unsubscribe'] = array(
    'title' => 'Subscribe',
    'class' => 'WangxbUnsubscribeAction',
    'description' => 'The event fire when user subscribe my weixin.',
    'type' => WEIXIN_ROUTER_TYPE_EVENT,
  );
  $actions['node'] = array(
    'title' => 'Node list',
    'class' => 'WangxbNodeListAction',
    'description' => 'Return node list.',
    'type' => WEIXIN_ROUTER_TYPE_TEXT,
    'response class' => 'WeixinArticleResponse',
  );
  return $actions;
}

/**
 * Implements hook_weixin_router_alter()
 * preprocess alter router, set a default action
 */
function weixin_wangxb_weixin_router_alter(&$router) {
  $router->setDefaultAction(new WangxbDefaultAction(WeixinRequest::requestFromPost()));
}
